### ISSUE TITLE
Failed to host the dotnet Web API Project

### ISSUE THREAD

**Issue by Zhao-Michael** [smx-smx/EzDotnet#2]
System.MissingMethodException:“Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.Hosting.HostApplicationBuilder.get_Services()'.”

<Project Sdk="Microsoft.NET.Sdk.Web">

**Comment by smx-smx** [comment]
I cannot reproduce, using https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio as sample.

I however had to add `ASPNETCORE_PREVENTHOSTINGSTARTUP=1` to prevent the following exception:

```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[11]
      Hosting startup assembly exception
      System.InvalidOperationException: Startup assembly  failed to execute. See the inner exception for more details.
       ---> System.ArgumentException: The value cannot be an empty string. (Parameter 'assemblyName')
         at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
         at System.Reflection.AssemblyName..ctor(String assemblyName)
         at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
         --- End of inner exception stack trace ---

```

Launch command for the .NET Core runtime:

```
$ ASPNETCORE_PREVENTHOSTINGSTARTUP=1 \
/p/projects/OPENSOURCE/TodoApi/EzDotnet/build/samples/cli/ezdotnet.exe \
/p/projects/OPENSOURCE/TodoApi/EzDotnet/build/CoreCLR/libcoreclrhost.dll \
/p/projects/OPENSOURCE/TodoApi/bin/Release/net8.0/win-x64/TodoApi.dll \
Program Entry
```

Output: 
```
Handle: 00007ffab6490000
calling clrInit, pwd: P:\projects\OPENSOURCE\TodoApi\bin\Release\net8.0\win-x64, asm: P:/projects/OPENSOURCE/TodoApi/bin/Release/net8.0/win-x64/To
doApi.dll
[clrInit]:
calling runMethod, handle: 1343733333
[runMethod]:
[runMethod]: Loading 'P:/projects/OPENSOURCE/TodoApi/bin/Release/net8.0/win-x64/TodoApi.dll', then running Entry in Program,TodoApi
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: P:\projects\OPENSOURCE\TodoApi\bin\Release\net8.0\win-x64
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

```

**Comment by Zhao-Michael** [comment]
Well... Without inject services, it can work.

Did you add some service into the web app builder?
for example add this code before builder.Build();  : builder.Services.AddControllers();

**Comment by Zhao-Michael** [comment]
Sorry, My Problem. It can work now.

**Comment by smx-smx** [comment]
Ok, I think I figured it out.
It's related to missing APP_CONTEXT properties that need to be set from native code, namely:
- APP_CONTEXT_BASE_DIRECTORY
- APP_PATHS 

And possibly a few others. AspNet Core uses reflection to load further assemblies, and that code will fail if those aren't set.
This might also be relevant if we want to support self contained apps in the future.

I'll wrap up a fix shortly :)

**Comment by smx-smx** [comment]
I pushed a fix which was validated on my end.
Let me know if it works for you, so we can close this for good.

**Comment by Zhao-Michael** [comment]
Thanks for your help!

inject services can work now.

But I found new problem: It still failed to host AspNet Core Project when I add this log package in my dotnet project:

PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1"

**Comment by smx-smx** [comment]
I reproduced it too but, from what i'm reading, you shouldn't use the `.Abstractions` package alone (From what I understood, it doesn't contain concrete types. You need the packages containing the actual implementation.)

I fixed it by installing the following:
- Microsoft.Extensions.Logging
- Microsoft.Extensions.DependencyInjection

As to why this is necessary, i'm not completely sure yet.
My guess is that there's some implicit dependency to those 2 packages that is missing when doing "dotnet publish" vs a standard run.

In that case, it might not be a bug with EzDotnet but could rather be the result of optimization.

**Comment by Zhao-Michael** [comment]
My project use SignalR, Add Microsoft.Extensions.Logging, Microsoft.Extensions.DependencyInjection still not work...😥

PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8"
PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="8.0.8"
PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="8.0.8"
PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="8.0.8"

I am not sure If It's caused by EzDotnet.

**Comment by smx-smx** [comment]
Could you provide a stack trace? Or some more information? Or even better a repro project?

**Comment by Zhao-Michael** [comment]
[PluginDemo.zip](https://github.com/user-attachments/files/16832715/PluginDemo.zip)


ezdotnet.exe "E:\git\cpp\EzDotnet\x64\Debug\coreclrhost.dll" "E:\codes\ConsoleApp1\PluginDemo\bin\Debug\net8.0\PluginDemo.dll" "Traffic.Monitor" "Entry"



Handle: 00007FFE70FD0000
calling clrInit, pwd: E:\git\cpp\EzDotnet\samples\cli\Debug, asm: E:\codes\ConsoleApp1\PluginDemo\bin\Debug\net8.0\PluginDemo.dll
[clrInit]:
[initHostFxr]: host_path: E:\codes\ConsoleApp1\PluginDemo\bin\Debug\net8.0
calling runMethod, handle: 4123713130
[runMethod]:
[runMethod]: Loading 'E:\codes\ConsoleApp1\PluginDemo\bin\Debug\net8.0\PluginDemo.dll', then running Entry in Traffic.Monitor,PluginDemo
Unhandled exception. System.AggregateException: One or more errors occurred. (Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.)
 ---> System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder..ctor()
   at PluginDemo.Program.Go(String[] args) in E:\codes\ConsoleApp1\PluginDemo\Program.cs:line 14
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Traffic.Monitor.Entry(IntPtr args, Int32 sizeBytes) in E:\codes\ConsoleApp1\PluginDemo\Monitor.cs:line 9

**Comment by smx-smx** [comment]
Thanks for the sample. Just fyi, I'm currently not at home and it will take a while before I can take a look at it.
I'll let you know as soon as I have the chance to check it out.

**Comment by smx-smx** [comment]
I'm looking at it.
I haven't figured it out yet but I suspect it might be related to the way `hostpolicy` is getting initialized.

If you set `COREHOST_TRACE=1` and `COREHOST_TRACE_VERBOSITY=4` and then run both
- ezdotnet (which throws the exception)
- the published app's exe (which works)

you can see the differences in dependency resolution.
by comparing the 2 I see that, in the working case, the deps file (`PluginDemo.deps.json`) is loaded early and `hostpolicy` is initialized in `apphost` mode.

In ezdotnet, it's initialized as `libhost` and the deps json is considered later on.

This difference is likely due to me using `hostfxr_initialize_for_runtime_config` rather than `hostfxr_initialize_for_dotnet_command_line`.

According to [the docs](https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md):

>    hostfxr_initialize_for_dotnet_command_line - this is the initialize for an application. The API is a bit more complicated as it allows for command line parsing as well. Eventually we might want to add another "initialize app" API without the command line support.
>    hostfxr_initialize_for_runtime_config - this is the initialize for a component (naming is not ideal, but can't be changed anymore).

So it seems that I'll have to try with the dotnet command line API to simulate an invocation from "dotnet run"

For what it's worth, I took a quick look at the .NET source code and indeed there's a variable called `is_app` which is set differently depending on how the runtime was initialized.

**Comment by smx-smx** [comment]
Thanks to @vitek-karas for the help, and pointing out about `get_function_pointer_fn`.
The issue is that `load_assembly_and_get_function_pointer_fn` performs an additional assembly load, on top of the one already loaded for the first Assembly Load Context (ALC).

The second assembly load is performed in a different ALC, and is always assumed to be of "component" (library) type, which is why some dependencies are missing.

`get_function_pointer_fn` is .NET 5+ only, so we'd be breaking support for .NET Core 3, but it will do for now.

We can eventually come back to .NET Core 3 later if the need arises.

**Comment by smx-smx** [comment]
@Zhao-Michael I can successfully run the sample with the latest changes. Can you try again and let me know?

**Comment by Zhao-Michael** [comment]
It works!

Thanks for your great job!

Please give me more time to do more test! 

Hope no more bugs are found~ 😄
